platform :ios, '5.0' 
# Or platform :osx, '10.7'
pod 'RestKit', '~> 0.20.1'
pod 'Three20', '~> 1.0.11'
pod 'Nimbus', '~> 1.0.0'
pod 'MTStatusBarOverlay', '~> 0.9.1'
pod 'JSONKit', '~> 1.5pre'
pod 'SinaWeibo', '~> 0.0.1'
pod 'MFSideMenu', '~> 0.4.1'
pod 'CrittercismSDK', '~> 3.4.9'
# pod 'WEPopover', '~> 0.0.1'
pod 'WEPopover@krzd', '~> 0.1.0'
pod 'TDBadgedCell', '~> 2.1'
pod 'AKSegmentedControl'
pod 'ODRefreshControl', '~> 1.1.0'
pod 'SBJson', '~> 3.2'
pod 'CMPopTipView', '~> 1.2.0'

# Testing and Search are optional components
# pod 'RestKit/Testing', '~> 0.20.0pre'
# pod 'RestKit/Search',  '~> 0.20.0pre'
